version: '3.4'
services:
  game_server:
    build: 
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - 8080:80
    environment:
      APP_NAME: MopconGameServer
      APP_ENV: local
      APP_KEY: base64:/0wMmMiuIQeu2J/gKa5jaXXR5Gj83JSCJHjt+kqed7Q=
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8080
      APP_LOCALE: zh_TW
      APP_TIMEZONE: Asia/Taipei
      ADMIN_KEY: gametest
      DB_CONNECTION: mysql
      DB_HOST: game_db
      DB_PORT: 3306
      DB_DATABASE: mopcon_gameserver
      DB_USERNAME: mopcon_gameserver
      DB_PASSWORD: 123456
      JWT_SECRET: RTRSsvVnnOXBCY2nMjyuudVlEzWDhczr9h76W63Mz2xQmOvD1krIQh6yCMuHyNq0
    depends_on: 
      - game_db
    volumes:
      - ./:/code

  game_db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mopcon_gameserver
      MYSQL_USER: mopcon_gameserver
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306

  game_admin:
    image: phpmyadmin:5.0.2
    environment:
      PMA_HOST: game_db
      PMA_PORT: 3306
      PMA_USER: mopcon_gameserver
      PMA_PASSWORD: 123456
    ports:
      - 8081:80
